services:
  db:
    image: postgres:16
    container_name: attendance_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: attendance
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d attendance"]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  pgdata:
